---
title: "Azimuth Squamous Lung Liftover"
format: html
date: "`r Sys.Date()`"
author: "Mobina Kazemi"
execute:
  cache: false
editor: visual  
---

```{r setup}
#| output: false
library(codetools)
library(tidyverse)
library(Seurat)
library(Azimuth)
library(SeuratData)
library(patchwork)
library(SeuratDisk)
library(anndata)
library(Matrix)
library(here)
library(survival)
library(Seurat)
library(SeuratDisk)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(devtools)
library(cowplot)
library(stringr)
library(reticulate)
setwd("/work/shah/users/Mobina/")
```

#Run Azimuth

```{r}
# To see available refs
available_data <- AvailableData()
available_data[grep("Azimuth", available_data[,3]), 1:3]
```

#load data

```{r}
seurat_data<-LoadH5Seurat(file = "/work/shah/users/Mobina/Project_Squamous/Squamousdata/Final_data.h5seurat")
adata_Full<-read_h5ad("/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_subtype_output.h5ad")

adata_Full<-read_h5ad("/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_genevector_from_top_with_subpops.h5ad)
seurat_data@meta.data$index<-rownames(seurat_data@meta.data)
seurat_data<-seurat_data[,rownames(adata_Full)]
```

```{r}
seurat_data <- RunAzimuth(seurat_data, reference = "lungref")
```

#Merge datasets

```{r}
adata_Full$obs<-merge(adata_Full$obs,seurat_data@meta.data[,c(4,seq(8,20))],by="index")
```

#Save metadata

```{r}
seurat_data@meta.data %>%
  as.data.frame() %>%
  rownames_to_column(var = "cell_id") %>%
  write.table(file="/work/shah/users/Mobina/squamous_cell_analysis/Azimuth/squamous_lungref_azimuth_refmapped.txt", quote = F, sep = "\t", row.names = F, col.names = T)

# R.utils::gzip("sclc_lungref_azimuth_refmapped.txt", overwrite = TRUE)
```

#Compare the results

```{r}
Compare_genevector_level3<-adata_Full$obs %>% group_by(predicted.ann_level_3,genevector) %>% count()
Compare_leiden_level3<-adata_Full$obs %>% group_by(predicted.ann_level_3,leiden) %>% count()
```

#Load infercnv results

```{r}
infer_cnv<-read.delim("/work/shah/users/Mobina/squamous_cell_analysis/cnv/infercnv/infercnv_results.txt")
with(infer_cnv, table(is_tumor_cell, cell_type))
```

#Merge data with infercnv esults

```{r}
infer_cnv$index<-infer_cnv$cell_id
adata_Full$obs<-merge(adata_Full$obs,infer_cnv[,3:8],by="index")
a<-with(adata_Full$obs, table(is_tumor_cell, genevector))

a<-as.data.frame(a)
ggplot(a, aes(fill=is_tumor_cell, y=Freq, x=genevector)) + 
    geom_bar(position="dodge", stat="identity")

```
```{r}
adata_Full$obs$genevector_l2<-as.character(adata_Full$obs$genevector_l2)
adata_Full$obs$genevector_l2[adata_Full$obs$index %in% infer_cnv$cell_id[which(infer_cnv$is_tumor_cell==T)]]="Cancer"
```

```{r}
with(adata_Full$obs, table(is_tumor_cell, genevector_l2))
```

#update lables

```{r}
adata_Full$obs$leiden<-as.character(adata_Full$obs$leiden)
adata_Full$obs$leiden[(which(adata_Full$obs$genevector=="Cancer" & adata_Full$obs$is_tumor_cell==FALSE))]<-"Epithelial"

adata_Full$obs$genevector_updated<-adata_Full$obs$genevector
adata_Full$obs$genevector_updated<-as.character(adata_Full$obs$genevector_updated)

adata_Full$obs$genevector_updated[(which(adata_Full$obs$genevector=="Cancer" & adata_Full$obs$is_tumor_cell==FALSE))]<-"Epithelial"
with(adata_Full$obs, table(is_tumor_cell, leiden))
```

#Save the final adata to load in python for the other analysis

```{r}
4779+13+6+40+7+136+171
#write_h5ad(adata_Full, "/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_liftover_output.h5ad")
```

#Do a plot and save out

```{r}
#| fig-width: 8
#| fig-height: 20
p1a <- DimPlot(seurat_data, group.by = "predicted.ann_level_1", label = TRUE, label.size = 3) + NoLegend()
p1b <- VlnPlot(seurat_data, features = "predicted.ann_level_1.score", group.by = "predicted.ann_level_1", pt.size = 0) + NoLegend()
p2a <- DimPlot(seurat_data, group.by = "predicted.ann_level_2", label = TRUE, label.size = 3) + NoLegend()
p2b <- VlnPlot(seurat_data, features = "predicted.ann_level_2.score", group.by = "predicted.ann_level_2", pt.size = 0) + NoLegend()

p3a <- DimPlot(seurat_data, group.by = "predicted.ann_level_3", label = TRUE, label.size = 3) + NoLegend()
p3b <- VlnPlot(seurat_data, features = "predicted.ann_level_3.score", group.by = "predicted.ann_level_3", pt.size = 0) + NoLegend()

p4a <- DimPlot(seurat_data, group.by = "predicted.ann_level_4", label = TRUE, label.size = 3) + NoLegend()
p4b <- VlnPlot(seurat_data, features = "predicted.ann_level_4.score", group.by = "predicted.ann_level_4", pt.size = 0) + NoLegend()

p5a <- DimPlot(seurat_data, group.by = "predicted.ann_level_5", label = TRUE, label.size = 3) + NoLegend()
p5b <- VlnPlot(seurat_data, features = "predicted.ann_level_5.score", group.by = "predicted.ann_level_5", pt.size = 0) + NoLegend()


p6a <- DimPlot(seurat_data, group.by = "predicted.ann_finest_level", label = TRUE, label.size = 3) + NoLegend()
p6b <- VlnPlot(seurat_data, features = "predicted.ann_finest_level.score", group.by = "predicted.ann_finest_level", pt.size = 0) + NoLegend()

# Grab all plots
p_list <- mget(ls(pattern = "p.[ab]"))

# pcomb <- wrap_plots(p_list, ncol = 2)

#SaveH5Seurat(seurat_data, filename = "til_lung_liftover")

pdf("/work/shah/users/Mobina/squamous_cell_analysis/Azimuth/Squamous_lung_liftover.pdf", width = 12, height = 8, onefile = TRUE)
print(p_list)
dev.off()

```

Filter the h5ad file and update the cell types

```{r}
adata_Full$obs$genevector_updated<-as.character(adata_Full$obs$genevector_updated)
adata_Full$obs$leiden<-as.character(adata_Full$obs$leiden)
adata_Full$obs$genevector_updated[which(adata_Full$obs$predicted.ann_level_4=="Plasmacytoid DCs")]="Plasmacytoid_DCs"
adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="1_Myeloid")]="B Cell"
adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="4_Myeloid")]="B Cell"
adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="2_Myeloid")]="Mast Cell"

adata_Full$obs$predicted.ann_level_3<-as.character(adata_Full$obs$predicted.ann_level_3)
adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="3_Myeloid")]=adata_Full$obs$predicted.ann_level_3[which(adata_Full$obs$leiden=="3_Myeloid")]

adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="0_Myeloid")]=adata_Full$obs$predicted.ann_level_3[which(adata_Full$obs$leiden=="0_Myeloid")]

adata_Full$obs$genevector_updated[which(adata_Full$obs$leiden=="5_Myeloid")]=adata_Full$obs$predicted.ann_level_3[which(adata_Full$obs$leiden=="5_Myeloid")]

adata_Full$obs$genevector_updated<-gsub(pattern ="B Cell" ,replacement ="B_Cell" ,x =adata_Full$obs$genevector_updated )

adata_Full$obs$genevector_updated<-gsub(pattern ="B cell lineage" ,replacement ="B_Cell" ,x =adata_Full$obs$genevector_updated )

adata_Full$obs$genevector_updated<-gsub(pattern =" " ,replacement ="_" ,x =adata_Full$obs$genevector_updated )

adata_Full$obs$genevector_updated<-gsub(pattern ="T_cell_lineage" ,replacement ="T_Cell" ,x =adata_Full$obs$genevector_updated )

adata_Full$obs$genevector_updated<-gsub(pattern ="Mast_cells" ,replacement ="Mast_Cell" ,x =adata_Full$obs$genevector_updated )

adata_Full$obs$genevector_updated<-gsub(pattern ="Fibroblasts" ,replacement ="Fibroblast" ,x =adata_Full$obs$genevector_updated )

Frequency_clusters<-as.data.frame(table(adata_Full$obs$genevector_updated))
````

```{r}
table(adata_Full$obs$genevector_updated[which(adata_Full$obs$predicted.ann_level_2=="Myeloid")])
table(adata_Full$obs$predicted.ann_level_3[which(adata_Full$obs$predicted.ann_level_2=="Myeloid")])
table(adata_Full$obs$predicted.ann_level_4[which(adata_Full$obs$predicted.ann_level_2=="Myeloid")])

Data_myeloid_liftover<-adata_Full[which(adata_Full$obs$predicted.ann_level_2=="Myeloid"),]
#write_h5ad(Data_myeloid_liftover, "/work/shah/users/Mobina/Project_Squamous/Squamousdata/Data_myeloid_liftover.h5ad")
Data_myeloid_liftover<-read_h5ad("/work/shah/users/Mobina/Project_Squamous/Squamousdata/Data_myeloid_liftover.h5ad")
table(Data_myeloid_liftover$obs$genevector_updated[which(Data_myeloid_liftover$obs$predicted.ann_level_2=="Myeloid")])

a<-with(adata_Full$obs, table(is_tumor_cell, genevector))

a<-as.data.frame(a)
ggplot(a, aes(fill=is_tumor_cell, y=Freq, x=genevector)) + 
    geom_bar(position="dodge", stat="identity")

```

#Remove unkown and everything with less than 20 cells
```{r}
adata_Full_1<-adata_Full[adata_Full$obs$genevector_updated %in% Frequency_clusters$Var1[which(Frequency_clusters$Freq>20)]]

adata_Full_2<-adata_Full_1[which(adata_Full_1$obs$genevector_updated !="Unknown")]


write_h5ad(adata_Full_2, "/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_subtype_output_filtered.h5ad")
write_h5ad(adata_Full_1, "/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_subtype_output_filtered_with_Unknown.h5ad")
```
```{r}
adata_Full<-read_h5ad("/work/shah/users/Mobina/Project_Squamous/Squamousdata/adata_Full_subtype_output_filtered_with_Unknown.h5ad")

```

